using System;
using System.Data;
using System.Diagnostics;

namespace EntityFrameworkCore.Generator.Metadata.Generation
{
    [DebuggerDisplay("Property: {PropertyName}, Column: {ColumnName}, Type: {NativeType}")]
    public class Property : ModelBase
    {
        public string PropertyName { get; set; }
        public string ColumnName { get; set; }

        public DbType DataType { get; set; }
        public string NativeType { get; set; }

        public Type SystemType { get; set; }

        public int? Order { get; set; }

        public bool? IsNullable { get; set; }

        public bool IsRequired => IsNullable == false;

        public bool IsOptional => IsNullable == true;

        public bool? IsPrimaryKey { get; set; }
        public bool? IsForeignKey { get; set; }

        public bool? IsAutoGenerated { get; set; }
        public bool? IsReadOnly { get; set; }
        public bool? IsRowVersion { get; set; }
        public bool? IsIdentity { get; set; }
        public bool? IsUnique { get; set; }

        public bool? IsUnicode { get; set; }
        public bool? IsFixedLength { get; set; }

        public int? MaxLength { get; set; }

        public byte? Precision { get; set; }
        public int? Scale { get; set; }

        public string Default { get; set; }
    }
}
